config/routes.rb
Rails.application.routes.draw do
  resources :games, except: %i(show), shallow: true do
    resources :resources, except: %i(show)
    resources :resource_groups, except: %i(show)
    resources :dice, shallow: true, except: %i(show) do
      resources :faces, shallow: true, except: %i(show)
    end
    resources :rooms, shallow: true, except: %i(index) do
      resources :room_resources, except: %i(new create delete)
      resources :rolls, only: %i(index new create)
    end
  end
  devise_for :users

  get "/rooms/join/:join_code", to: "join_room#find_room", as: "find_room"
  post "/rooms/join/:join_code", to: "join_room#join_room", as: "join_room"

  root to: "home#index"
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :created_by, class_name: "User"
  has_many :dice, dependent: :destroy
  has_many :resources, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :resource_groups, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :created_by_id }
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user!
  before_action :set_game, only: %i(edit update destroy)
  authorize_resource

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    @game.created_by = current_user

    if @game.save
      redirect_to games_url, notice: "Game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    if @game.update(game_params)
      redirect_to games_url, notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    redirect_to games_url, notice: "Game was successfully destroyed."
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :created_by_id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, class: "contents") do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= render "shared/text_field", f: form, field: :name %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "btn-primary" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <h3 class="text-2xl mt-4"><%= game.name %></h3>
  <p>
    created by player <%= game.created_by.username %>
  </p>
  <div class="flex flex-wrap">
    <%= link_to 'Start Room', new_game_room_path(game), class: "btn-light" %>
    <%= link_to 'Dice', game_dice_path(game), class: "btn-light" %>
    <%= link_to 'Resources', game_resources_path(game), class: "btn-light" %>
    <%= link_to 'Resource Groups', game_resource_groups_path(game), class: "btn-light" %>
    <% if can? :manage, game %>
      <%= link_to 'Edit this game', edit_game_path(game), class: "btn-light" %>
      <%= button_to 'Delete', game, method: :delete, class: "btn-red", form_class: "inline" %>
    <% end %>
  </div>
  <hr class="mt-6">
</div>

app/views/games/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing game</h1>

  <%= render "form", game: @game %>

  <%= link_to "Show this game", @game, class: "btn-light" %>
  <%= link_to "Back to games", games_path, class: "btn-light" %>
</div>

app/views/games/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Games</h1>
    <%= link_to 'New game', new_game_path, class: "btn-light" %>
  </div>

  <div id="games" class="min-w-full">
    <%= render @games %>
  </div>
</div>

app/views/games/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New game</h1>

  <%= render "form", game: @game %>

  <%= link_to 'Back to games', games_path, class: "btn-light" %>
</div>