config/routes.rb
Rails.application.routes.draw do
  resources :games, except: %i(show), shallow: true do
    resources :resources, except: %i(show)
    resources :resource_groups, except: %i(show)
    resources :dice, shallow: true, except: %i(show) do
      resources :faces, shallow: true, except: %i(show)
    end
    resources :rooms, shallow: true, except: %i(index) do
      resources :room_resources, except: %i(new create delete)
      resources :rolls, only: %i(index new create)
    end
  end
  devise_for :users

  get "/rooms/join/:join_code", to: "join_room#find_room", as: "find_room"
  post "/rooms/join/:join_code", to: "join_room#join_room", as: "join_room"

  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user
    die_ability
    face_ability
    game_ability
    resource_ability
    resource_group_ability
    room_ability
    roll_ability
    room_resource_ability
    user_room_ability
  end

private

  def die_ability
    can :show, Die
    can :manage, Die, game: { created_by_id: @user.id }
  end

  def face_ability
    can :show, Face
    can :manage, Face, die: { game: { created_by_id: @user.id } }
  end

  def game_ability
    can :show, Game
    can :manage, Game, created_by_id: @user.id
  end

  def resource_ability
    can :show, Resource
    can :manage, Resource, game: { created_by_id: @user.id }
  end

  def resource_group_ability
    can :show, ResourceGroup
    can :manage, ResourceGroup, game: { created_by_id: @user.id }
  end

  def room_ability
    can :show, Room do |room|
      room.users.include? @user
    end
    can :manage, Room, created_by_id: @user.id
  end

  def roll_ability
    can :manage, Roll, user_id: @user.id
  end

  def room_resource_ability
    can :manage, RoomResource do |room_resource|
      room_resource.user_id == @user.id || room_resource.room.users.include?(@user)
    end
  end

  def user_room_ability
    can :manage, UserRoom, user_id: @user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/die.rb
class Die < ApplicationRecord
  belongs_to :game
  has_many :faces, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :game_id }

  def roll(user:, room:, number: 1)
    rolled_faces = rolled_faces number
    roll = Roll.create! user: user, room: room
    roll_results_data = rolled_faces.map { |face| { face_id: face.id, roll_id: roll.id } }
    RollResult.insert_all! roll_results_data # rubocop:disable Rails/SkipsModelValidations
    roll.broadcast_roll
    roll
  end

private

  def rolled_faces(number)
    potential_results = []
    faces.each do |face|
      face.count.times do
        potential_results.push(face)
      end
    end
    Array.new(number.to_i).map do
      potential_results.sample
    end
  end
end

app/models/face.rb
class Face < ApplicationRecord
  belongs_to :die
  has_many :roll_results, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :die_id }
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :created_by, class_name: "User"
  has_many :dice, dependent: :destroy
  has_many :resources, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :resource_groups, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :created_by_id }
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :game
  belongs_to :resource_group, optional: true
  has_many :room_resources, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :game_id }

  after_create :sync_resources

  def sync_resources
    active_rooms = Room.where(game_id: game_id)
    active_rooms.each(&:sync_all_resources)
  end

  def group_name
    resource_group&.name || "Ungrouped"
  end
end

app/models/resource_group.rb
class ResourceGroup < ApplicationRecord
  belongs_to :game
  has_many :resources, dependent: :nullify

  validates :name, presence: true, uniqueness: { scope: :game_id }
end

app/models/roll.rb
class Roll < ApplicationRecord
  belongs_to :user
  belongs_to :room
  has_many :roll_results, dependent: :destroy

  scope :for_room_log, ->(room) { where(room: room).order(created_at: :desc).includes(:user, roll_results: :face) }

  def summary
    roll_results.map { |result| result.face.name }.tally
  end

  def summary_string
    summary_map = summary
    rolls = summary_map.map { |face, count| "#{face}: #{count}" }.join(" | ")
    "#{user.username} rolled #{rolls}"
  end

  def broadcast_roll
    broadcast_append_to "room-#{room.id}", partial: "layouts/notification", locals: { message: summary_string },
                                           target: "notifications"
    broadcast_prepend_to "room_#{room.id}_rolls"
  end
end

app/models/roll_result.rb
class RollResult < ApplicationRecord
  belongs_to :face
  belongs_to :roll
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :game
  belongs_to :created_by, class_name: "User"
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :room_resources, dependent: :destroy
  has_many :resources, through: :room_resources
  has_many :rolls, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :created_by_id }

  after_create :just_created

  def sync_all_resources
    sync_global_resources
    sync_player_resources
  end

  def grouped_resources_for_player(user:)
    {
      global: RoomResource.where(user: nil, room: self).group_by(&:group_name),
      player: RoomResource.where(user: user, room: self).group_by(&:group_name)
    }
  end

private

  def just_created
    users << created_by
    sync_all_resources
  end

  def sync_global_resources
    global_resources = Resource.where(global: true, game: game)
    global_resources.each do |resource|
      RoomResource.find_or_create_by(
        user: nil,
        room: self,
        resource: resource
      )
    end
  end

  def sync_player_resources
    player_resources = Resource.where(global: false, game: game)
    user_rooms.reload.each do |user_room|
      player_resources.each do |resource|
        RoomResource.find_or_create_by(
          user: user_room.user,
          room: self,
          resource: resource
        )
      end
    end
  end
end

app/models/room_resource.rb
class RoomResource < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :resource
  belongs_to :room

  validates :resource, uniqueness: { scope: %i(user_id room_id) }

  after_save :broadcast_update

  scope :other_players, ->(room, active_user) { where(room: room).where.not(user: active_user).joins(:user) }

  delegate :group_name, to: :resource

  def broadcast_update
    broadcast_replace_to "room-#{room.id}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy, foreign_key: :created_by_id, inverse_of: false
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
  has_many :room_resources, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :username, length: { maximum: 60 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :user, uniqueness: { scope: :room_id }

  after_create -> { room.sync_all_resources }

  def sync_resources
    room.sync_all_resources
  end

  def resources_by_group
    group_map = {}
    room_resources.each do |room_resource|
      if group_map.key? room_resource.resource.group_name
        group_map[room_resource.resource.group_name].push room_resource
      else
        group_map[room_resource.resource.group_name] = [room_resource]
      end
    end
    group_map
  end

  def room_resources
    RoomResource.where(user: user, room: room)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/dice_helper.rb
module DiceHelper
end

app/helpers/faces_helper.rb
module FacesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/join_room_helper.rb
module JoinRoomHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/resources/_form.html.erb
<%= form_with(model: [game, resource], class: "contents") do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= render "shared/text_field", f: form, field: :name %>
  </div>

  <div class="my-5">
    <%= form.label :resource_group, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.select :resource_group_id, resource_group_options, {}, {class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"} %>
  </div>

  <div class="my-5">
    <%= render "shared/number_field", f: form, field: :min %>
  </div>

  <div class="my-5">
    <%= render "shared/number_field", f: form, field: :max %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "btn-primary" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= resource.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Group:</strong>
    <%= resource.resource_group&.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Min:</strong>
    <%= resource.min %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Max:</strong>
    <%= resource.max %>
  </p>
  <div class="flex flex-wrap">
    <%= link_to "Show this resource", resource, class: "btn-light" %>
    <% if can? :manage, resource %>
      <%= link_to 'Edit this resource', edit_resource_path(resource), class: "btn-light" %>
      <%= button_to 'Delete', resource, method: :delete, class: "btn-red", form_class: "inline" %>
    <% end %>
  </div>
  <hr class="mt-6">
</div>

app/views/resources/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing resource</h1>

  <%= render "form", resource: @resource, game: nil, resource_group_options: @resource_group_options %>

  <%= link_to "Show this resource", @resource, class: "btn-light" %>
  <%= link_to "Back to resources", game_resources_path(@resource.game), class: "btn-light" %>
</div>

app/views/resources/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Resources for <%= @game.name %></h1>
    <% if can? :manage, @game %>
      <%= link_to 'New resource', new_game_resource_path(@game), class: "btn-light" %>
    <% end %>
  </div>

  <div id="resources" class="min-w-full">
    <%= render @resources %>
  </div>
</div>

app/views/resources/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New resource</h1>

  <%= render "form", game: @game, resource: @resource, resource_group_options: @resource_group_options %>

  <%= link_to 'Back to resources', game_resources_path(@game), class: "btn-light" %>
</div>

app/views/shared/_drawer.html.erb
<div>
  <button class="btn-primary" 
    type="button" 
    data-drawer-target="<%= drawer_id %>" 
    data-drawer-toggle="<%= drawer_id %>" 
    data-drawer-placement="right" 
    aria-controls="<%= drawer_id %>"
  >
    <%= show_button_text %>
  </button>
  <div id="<%= drawer_id %>" class="fixed top-0 right-0 z-40 h-screen p-4 overflow-y-auto transition-transform translate-x-full bg-white w-80 dark:bg-gray-800" tabindex="-1" aria-labelledby="drawer-right-label">
    <button 
    type="button" 
    data-drawer-hide="<%= drawer_id %>" 
    aria-controls="<%= drawer_id %>" 
    class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 absolute top-2.5 right-2.5 inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" >
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      <span class="sr-only">Close menu</span>
    </button>
    <%= yield %>
  </div>
</div>

app/views/shared/_number_field.html.erb
<%= f.label field, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
<%= f.number_field field, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>

app/views/shared/_password_field.html.erb
<%= f.label field, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
<%= f.password_field field, autocomplete: autocomplete, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>

app/views/shared/_skeleton.html.erb
<div role="status" class="max-w-sm animate-pulse">
  <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[330px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[300px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5"></div>
  <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[330px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[300px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5"></div>
  <div class="h-2.5 bg-gray-200 rounded-full dark:bg-gray-700 w-48 mb-4"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[330px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[300px] mb-2.5"></div>
  <div class="h-2 bg-gray-200 rounded-full dark:bg-gray-700 max-w-[360px] mb-2.5]"></div>
  <span class="sr-only">Loading...</span>
</div>

app/views/shared/_text_field.html.erb
<% autocomplete ||= nil %>
<%= f.label field, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
<%= f.text_field field, autocomplete: autocomplete, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>