config/routes.rb
Rails.application.routes.draw do
  resources :games, except: %i(show), shallow: true do
    resources :resources, except: %i(show)
    resources :resource_groups, except: %i(show)
    resources :dice, shallow: true, except: %i(show) do
      resources :faces, shallow: true, except: %i(show)
    end
    resources :rooms, shallow: true, except: %i(index) do
      resources :room_resources, except: %i(new create delete)
      resources :rolls, only: %i(index new create)
    end
  end
  devise_for :users

  get "/rooms/join/:join_code", to: "join_room#find_room", as: "find_room"
  post "/rooms/join/:join_code", to: "join_room#join_room", as: "join_room"

  root to: "home#index"
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :game
  belongs_to :created_by, class_name: "User"
  has_many :user_rooms, dependent: :destroy
  has_many :users, through: :user_rooms
  has_many :room_resources, dependent: :destroy
  has_many :resources, through: :room_resources
  has_many :rolls, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :created_by_id }

  after_create :just_created

  def sync_all_resources
    sync_global_resources
    sync_player_resources
  end

  def grouped_resources_for_player(user:)
    {
      global: RoomResource.where(user: nil, room: self).group_by(&:group_name),
      player: RoomResource.where(user: user, room: self).group_by(&:group_name)
    }
  end

private

  def just_created
    users << created_by
    sync_all_resources
  end

  def sync_global_resources
    global_resources = Resource.where(global: true, game: game)
    global_resources.each do |resource|
      RoomResource.find_or_create_by(
        user: nil,
        room: self,
        resource: resource
      )
    end
  end

  def sync_player_resources
    player_resources = Resource.where(global: false, game: game)
    user_rooms.reload.each do |user_room|
      player_resources.each do |resource|
        RoomResource.find_or_create_by(
          user: user_room.user,
          room: self,
          resource: resource
        )
      end
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: %i(new create)
  before_action :set_room, only: %i(show edit update destroy)
  authorize_resource

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = @game.rooms.build
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.game = @game
    @room.created_by = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to games_path, notice: "Room was successfully destroyed." }
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  def set_game
    @game = Game.find(params[:game_id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:game_id, :name, :created_by_id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_dice.html.erb
<h3 class="mt-4 font-bold text-lg">
  Dice
</h3>
<div class="flex flex-wrap">
  <% dice.each do |die| %>
    <div id="<%= die.id %>">
      <button 
        id="die-button-<%= die.id %>"
        class="btn-primary"
        data-dropdown-toggle="dropdown-dice-<%= die.id %>"
      >
        <%= die.name %>
        <svg 
          class="w-4 h-4 ml-2 inline" 
          aria-hidden="true" 
          fill="none" 
          stroke="currentColor" 
          viewBox="0 0 24 24" 
          xmlns="http://www.w3.org/2000/svg"
        >
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
        </svg>
      </button>
      <div id="dropdown-dice-<%= die.id %>" class="flex flex-wrap z-10 hidden bg-white rounded-lg shadow dark:bg-gray-700 p-4">
        <% roll_options.each do |number| %>
          <%= button_to number, roll_dice_path(@room, die, number), method: :post, class: "text-gray-900 bg-gray-50 border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700", form_class: "inline" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/_form.html.erb
<%= form_with(model: [game, room], class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= render "shared/text_field", f: form, field: :name %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "btn-primary" %>
  </div>
<% end %>

app/views/rooms/_resources.html.erb
<% resources_by_group.each do |type, group| %>
  <h2 class="font-bold text-2xl"><%= type %></h2>
  <% group.each do |group_name, resources| %>
    <div>
      <h3 class="font-bold text-lg"><%= group_name %></h3>
      <div class="flex">
        <% resources.each do |user_resource| %>
          <div data-controller="room-resource" id="resource-<%= user_resource.id %>">
            <data data-room-resource-target="id" id="<%= user_resource.id %>"></data>
            <button
              class="btn-primary"
              id="resource-button-<%= user_resource.resource.id %>"
              data-dropdown-toggle="dropdown-<%= user_resource.id %>"
            >
              <%= render user_resource %>
              <svg 
                class="w-4 h-4 ml-2 inline" 
                aria-hidden="true" 
                fill="none" 
                stroke="currentColor" 
                viewBox="0 0 24 24" 
                xmlns="http://www.w3.org/2000/svg"
              >
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
              </svg>
            </button>
            <div id="dropdown-<%= user_resource.id %>" class="flex gap-2 z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 p-4">
              <button data-action="click->room-resource#decrement" class="text-4xl inline-block text-white border-2 border-red-600 rounded-md px-2 bg-red-500">-1</button>
              <button data-action="click->room-resource#increment" class="text-4xl inline-block text-white border-2 border-slate-600 rounded-md px-2 bg-green-500">+1</button>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/rooms/_roll.html.erb
<div data-controller="dismiss" id="roll-<%= roll.id %>" class="flex items-center w-full max-w-xs p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" role="alert">
  <div class="ml-3 text-sm font-normal"><%= roll.summary_string %></div>
  <button id="dismiss-roll-<%= roll.id %>" data-action="click->dismiss#dismiss" type="button" class="ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" aria-label="Close">
    <span class="sr-only">Close</span>
    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
  </button>
</div>

app/views/rooms/_roll_log_entry.html.erb
<div id="roll-log-entry<%= roll.id %>">
  <p class="my-2"><%= roll.summary_string %></p>
  <hr>
</div>

app/views/rooms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing room</h1>

  <%= render "form", room: @room, game: nil %>

  <%= link_to "Show this room", @room, class: "btn-light" %>
  <%= link_to "Back to rooms", game_rooms_path(@room.game), class: "btn-light" %>
</div>

app/views/rooms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Creating room for <%= @game.name %></h1>

  <%= render "form", room: @room, game: @game %>

  <%= link_to 'Back to rooms', game_rooms_path(@game), class: "btn-light" %>
</div>

app/views/rooms/roll.turbo_stream.erb
<%= turbo_stream.append "rolls", partial: "play/roll", locals: { roll: @roll } %>
<%= turbo_stream.prepend "roll-log", partial: "play/roll_log_entry", locals: { roll: @roll } %>

app/views/rooms/show.html.erb
<%= turbo_stream_from "room-#{@room.id}" %>

<div class="flex flex-col gap-2">
  <h1>Playing <%= @room.name %></h1>
  <% if can? :manage, @room %>
    <p class="bg-slate-200 rounded-md p-4"><%= find_room_url(@room.join_code) %></p>
    <div class="flex flex-wrap">
      <%= link_to 'Edit this room', edit_room_path(@room), class: "btn-light" %>
      <%= button_to 'Delete', room_path(@room), method: :delete, class: "btn-red", form_class: "inline" %>
    </div>
  <% end %>
</div>


<h1>Playing <%= @room.game.name %></h1>
<div class="flex gap-2">
  <%= render "shared/drawer", show_button_text: "Roll Log", drawer_id: "dice-rolls-drawer" do %>
    <div id="roll-log">
      <%= turbo_frame_tag "room_#{@room.id}_rolls", src: room_rolls_path(@room), loading: :lazy do %>
        <%= render "shared/skeleton" %>
      <% end %>
    </div>
  <% end %>
</div>
<%= turbo_frame_tag "room_#{@room.id}_room_resources", src: room_room_resources_path(@room), loading: :lazy do %>
  <%= render "shared/skeleton" %>
<% end %>

<%= turbo_frame_tag "room_#{@room.id}_rolls_new", src: new_room_roll_path(@room), loading: :lazy do %>
  <%= render "shared/skeleton" %>
<% end %>