config/routes.rb
Rails.application.routes.draw do
  resources :games, except: %i(show), shallow: true do
    resources :resources, except: %i(show)
    resources :resource_groups, except: %i(show)
    resources :dice, shallow: true, except: %i(show) do
      resources :faces, shallow: true, except: %i(show)
    end
    resources :rooms, shallow: true, except: %i(index) do
      resources :room_resources, except: %i(new create delete)
      resources :rolls, only: %i(index new create)
    end
  end
  devise_for :users

  get "/rooms/join/:join_code", to: "join_room#find_room", as: "find_room"
  post "/rooms/join/:join_code", to: "join_room#join_room", as: "join_room"

  root to: "home#index"
end

app/models/face.rb
class Face < ApplicationRecord
  belongs_to :die
  has_many :roll_results, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :die_id }
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_die, only: %i(index new create)
  before_action :set_face, only: %i(edit update destroy)
  authorize_resource

  # GET /faces or /faces.json
  def index
    @faces = @die.faces
  end

  # GET /faces/new
  def new
    authorize! :manage, @die
    @face = @die.faces.build
  end

  # GET /faces/1/edit
  def edit; end

  # POST /faces or /faces.json
  def create
    authorize! :manage, @die
    @face = Face.new(face_params)
    @face.die = @die

    respond_to do |format|
      if @face.save
        format.html { redirect_to die_faces_url(@die), notice: "Face was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faces/1 or /faces/1.json
  def update
    respond_to do |format|
      if @face.update(face_params)
        format.html { redirect_to die_faces_url(@face.die), notice: "Face was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faces/1 or /faces/1.json
  def destroy
    die = @face.die
    @face.destroy

    respond_to do |format|
      format.html { redirect_to die_faces_url(die), notice: "Face was successfully destroyed." }
    end
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_face
    @face = Face.find(params[:id])
  end

  def set_die
    @die = Die.find(params[:die_id])
  end

  # Only allow a list of trusted parameters through.
  def face_params
    params.require(:face).permit(:die_id, :name, :count)
  end
end

app/helpers/faces_helper.rb
module FacesHelper
end

app/views/faces/_face.html.erb
<div id="<%= dom_id face %>">

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= face.name %>: <%= face.count %></strong>
  </p>

  <div class="flex flex-wrap">
    <%= link_to "Show this face", face, class: "btn-light" %>
    <% if can? :manage, face %>
      <%= link_to 'Edit this face', edit_face_path(face), class: "btn-light" %>
      <%= button_to 'Delete', face, method: :delete, class: "btn-red", form_class: "inline" %>
    <% end %>
  </div>
  <hr class="mt-6">
</div>

app/views/faces/_form.html.erb
<%= form_with(model: [die, face], class: "contents") do |form| %>
  <% if face.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(face.errors.count, "error") %> prohibited this face from being saved:</h2>

      <ul>
        <% face.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= render "shared/text_field", f: form, field: :name %>
  </div>

  <div class="my-5">
    <%= render "shared/number_field", f: form, field: :count %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "btn-primary" %>
  </div>
<% end %>

app/views/faces/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing face</h1>

  <%= render "form", face: @face, die: nil %>

  <%= link_to "Show this face", @face, class: "btn-light" %>
  <%= link_to "Back to faces", die_faces_path(@face.die), class: "btn-light" %>
</div>

app/views/faces/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Faces for <%= @die.name %></h1>
    <%= link_to 'Back to dice', game_dice_path(@die.game), class: "btn-light" %>
    
    <% if can? :manage, @die %>
      <%= link_to 'New face', new_die_face_path(@die), class: "btn-light" %>
    <% end %>
    
  </div>

  <div id="faces" class="min-w-full">
    <%= render @faces %>
  </div>
</div>

app/views/faces/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New face</h1>

  <%= render "form", face: @face, die: @die %>

  <%= link_to 'Back to faces', die_faces_path(@die), class: "btn-light" %>
</div>